// Stages the three files a GitHub release must carry, into `release/`.
//
// This exists because `release/` was staged by hand once and then went stale.
// SHIPPING.md's `gh release create` command uploads from that folder, so a
// build made hours earlier would have gone out silently as 0.1.0 — the
// artifacts are opaque binaries and nothing about the command would have
// looked wrong. Anything a release depends on has to be regenerated by the
// release itself, not remembered.
//
// Run via `npm run release`, which builds first. It refuses to stage a build
// older than any source file, so the "I forgot to rebuild" version of the same
// mistake cannot happen either.

import { copyFileSync, existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const releaseDir = path.join(repoRoot, 'release');

/** Exactly what Obsidian expects, as loose files — never a zip, never a folder. */
const ARTIFACTS = ['main.js', 'manifest.json', 'styles.css'];

function newestMTime(dir) {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const t = entry.isDirectory() ? newestMTime(full) : statSync(full).mtimeMs;
    if (t > newest) newest = t;
  }
  return newest;
}

for (const name of ARTIFACTS) {
  if (!existsSync(path.join(repoRoot, name))) {
    console.error(`Missing ${name} — run \`npm run build\` first.`);
    process.exit(1);
  }
}

// `styles.css` and `manifest.json` are sources as well as artifacts, so only
// the bundle can be out of date with respect to `src/`.
const builtAt = statSync(path.join(repoRoot, 'main.js')).mtimeMs;
const sourceAt = newestMTime(path.join(repoRoot, 'src'));
if (builtAt < sourceAt) {
  console.error(
    'Refusing to stage: main.js is older than the newest file in src/.\n' +
      'Run `npm run build` (or `npm run release`, which builds first).',
  );
  process.exit(1);
}

for (const name of ARTIFACTS) {
  copyFileSync(path.join(repoRoot, name), path.join(releaseDir, name));
}

const { version } = JSON.parse(readFileSync(path.join(repoRoot, 'manifest.json'), 'utf8'));

console.log(`Staged release ${version} in release/`);
for (const name of ARTIFACTS) {
  const bytes = statSync(path.join(releaseDir, name)).size;
  console.log(`  ${name.padEnd(14)} ${bytes.toLocaleString()} bytes`);
}
console.log('\nUpload these three as loose files — not a zip, not a folder.');
